[versions]
agp = "8.7.2"
activity = "1.9.3"
material = "1.13.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

